/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JunitTesting;

import org.junit.Test;

import JunitTesting.Example;

import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.Before;

public class LibraryTest {
	@Before
	public void beforeEveryTesr() {
	System.out.println("-------------------------------");
	}

	@Test
	
	public void given_FirstNameis_Valid() {
	Example example =new Example();
	boolean result =Example.validatefirstname("Rushi");
	Assert.assertTrue("Happy",result);
}
	@Test
	
	public void given_FirstNameis_In_Valid() {
	Example example =new Example();
	boolean result =Example.validatefirstname("rushi");
	Assert.assertTrue("Sad",result);
}
@Test
	
	public void given_lastNameis_Valid() {
	Example example =new Example();
	boolean result =Example.validatelastname("Tayade");
	Assert.assertTrue("Happy",result);
}
	@Test
	
	public void given_lastNameis_In_Valid() {
	Example example =new Example();
	boolean result =Example.validatelastname("tayade");
	Assert.assertTrue("Sad",result);
}

	@Test
	
	public void given_emailId_is_Valid() {
	Example example =new Example();
	boolean result = Example.validatemailId("rushi147@gmail.com");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_emailId_is_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatemailId("rushi@147");
	Assert.assertTrue("Sad",result);
}
	@Test
	
	public void given_Password_Valid() {
	Example example =new Example();
	boolean result = Example.validatepassword("Ruushi@123");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_Password_Is_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatepassword("RRushi123");
	Assert.assertTrue("Sad",result);
}

	@Test
	
	public void given_Mobilenum_Valid() {
	Example example =new Example();
	boolean result = Example.validatemobilenum("9868574210");
	Assert.assertTrue("Happy",result);
}
@Test
	
	public void given_Mobilenum_In_Valid() {
	Example example =new Example();
	boolean result = Example.validatemobilenum("68059887099");
	Assert.assertTrue("Sad",result);
}

       
}

